language: generic

services:
  - docker

env:
  jobs:
    - IMAGE_TAG="${TRAVIS_COMMIT}" IMAGE_NAME="${DOCKER_USERNAME}/adaptive_learning_backend"
      NGINX_IMAGE_TAG="${TRAVIS_COMMIT}" NGINX_IMAGE_NAME="${DOCKER_USERNAME}/adaptive_learning_backend_nginx"
      POSTGRES_IMAGE_TAG="${TRAVIS_COMMIT}" POSTGRES_IMAGE_NAME="${DOCKER_USERNAME}/adaptive_learning_backend_postgres"

jobs:
  include:
    - stage: build
      before_script:
        - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
        - chmod +x .travis/build.sh
      script:
        - .travis/build.sh
    - stage: test
      before_script:
        - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
        - chmod +x .travis/test.sh
      script:
        - .travis/test.sh
