language: generic

services:
  - docker

env:
  jobs:
    - IMAGE_TAG="${TRAVIS_COMMIT}" IMAGE_NAME="${DOCKER_USERNAME}/adaptive_learning_backend"

jobs:
  include:
    - stage: build
      before_script:
        - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
        - chmod +x .travis/build.sh
      script:
        - .travis/build.sh
    - stage: test
      before_script:
        - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
        - chmod +x .travis/test.sh
        - docker-compose up -d postgres # start the db
      script:
        - .travis/test.sh
