language: generic

services:
  - docker
env:
  jobs:
    - IMAGE_TAG="$TRAVIS_COMMIT" # default tag value is the commit hash

jobs:
  include:
    - stage: build
      before_script:
        - chmod +x *.sh
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      script:
        - docker-compose build web # image is built and tagged
        - docker images # print images
        - docker push "$DOCKER_USERNAME"/adaptive_learning_backend:"$IMAGE_TAG" # push to repo
    - stage: test
      before_script:
        - docker-compose up -d postgres # start the db
      script:
        - docker-compose run --rm web ./test.sh