language: generic

services:
  - docker

env:
  global:
    - IMAGE_TAG="$TRAVIS_COMMIT" # default tag value is the commit hash

jobs:
  include:
    - stage: build
      before_script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      script:
        #- docker pull "$DOCKER_USERNAME"/adaptive_learning_backend # pulls latest image from dockerhub, for caching reasons when building new one
        - docker-compose build web # image is built and tagged
        - docker images # print images
        - docker push "$DOCKER_USERNAME"/adaptive_learning_backend:"$IMAGE_TAG" # push to repo
    - stage: test
      before_script:
        - docker-compose up -d postgres # start the db
      script:
        - docker pull "$DOCKER_USERNAME"/adaptive_learning_backend:"$IMAGE_TAG"
        - docker-compose run --rm web ./test.sh