language: python

services:
  - docker

before_install:
  - chmod +x test.sh
  - docker-compose up -d postgres # starts the db
  - docker-compose build web # build the django app container

script:
  - docker-compose run web ./test.sh # runs the tests
