language: generic

services:
  - docker

jobs:
  include:
    - stage: build
      before_script:
        - chmod +x *.sh
      script:
        - docker-compose build web
    - stage: test
      before_script:
        - docker-compose up -d postgres # start the db
      script:
        - docker-compose run web ./test.sh