version: "3.3"

networks:
  adaptive_learning_network:
    driver: bridge
services:

  nginx:
    image: "${NGINX_IMAGE_NAME}:${NGINX_IMAGE_TAG}"
    build:
      context: docker/nginx
    restart: always
    ports:
      - "80:80"
    networks:
      adaptive_learning_network:
    volumes:
      - web-static:/app/static
    depends_on:
      - web

  postgres:
    image: "${POSTGRES_IMAGE_NAME}:${POSTGRES_IMAGE_TAG}"
    build:
      context: docker/postgres
    restart: always
    environment:
      - POSTGRES_USER=secrethub://petrci1/adaptive_learning_backend/prod/postgres_user
      - POSTGRES_DB=secrethub://petrci1/adaptive_learning_backend/prod/postgres_db
      - POSTGRES_PASSWORD=secrethub://petrci1/adaptive_learning_backend/prod/postgres_password
      - SECRETHUB_CREDENTIAL
    networks:
      adaptive_learning_network:
    volumes:
      - pg:/var/lib/postgresql/data

  web:
    image: "${IMAGE_NAME}:${IMAGE_TAG}"
    build: 
      context: .
      target: prod
    environment:
      - ADAPTIVE_LEARNING_DB_USER=secrethub://petrci1/adaptive_learning_backend/prod/postgres_user
      - ADAPTIVE_LEARNING_DB_PASSWORD=secrethub://petrci1/adaptive_learning_backend/prod/postgres_password
      - ADAPTIVE_LEARNING_DB_NAME=secrethub://petrci1/adaptive_learning_backend/prod/postgres_db
      - ADAPTIVE_LEARNING_DB_HOST=postgres
      - ADAPTIVE_LEARNING_DB_PORT=5432
      - ADAPTIVE_LEARNING_SMTP_USER=secrethub://petrci1/adaptive_learning_backend/prod/smtp_user
      - ADAPTIVE_LEARNING_SMTP_PASSWORD:=secrethub://petrci1/adaptive_learning_backend/prod/smtp_password
      - SECRETHUB_CREDENTIAL
      - ADAPTIVE_LEARNING_DEBUG
    networks:
      adaptive_learning_network:
    depends_on:
      - postgres
    links:
      - postgres
    volumes:
      - web-static:/app/static

volumes:
  pg:
  web-static:
