# Generated by Django 3.2.4 on 2021-06-29 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_add_root_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluser',
            name='learning_material_preference',
            field=models.CharField(choices=[('visual', 'Visual'), ('verbal', 'Verbal')], default='Visual', max_length=100),
        ),
    ]
