name: CI

on: [ push ]


jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: secrethub/actions/env-export@v0.2.1
        env:
          SECRETHUB_CREDENTIAL: ${{ secrets.SECRETHUB_CREDENTIAL }}
          DOCKER_USERNAME: secrethub://petrci1/adaptive_learning_backend/dev/docker_username
          DOCKER_ACCESS_TOKEN: secrethub://petrci1/adaptive_learning_backend/dev/docker_token
          CC_TEST_REPORTER_ID: secrethub://petrci1/adaptive_learning_backend/dev/cc_test_reporter_id

      - run: |
          echo "IMAGE_TAG=$GITHUB_SHA" >> $GITHUB_ENV
          echo "NGINX_IMAGE_TAG=$GITHUB_SHA" >> $GITHUB_ENV
          echo "POSTGRES_IMAGE_TAG=$GITHUB_SHA" >> $GITHUB_ENV
          echo "IMAGE_NAME=$DOCKER_USERNAME/adaptive_learning_backend" >> $GITHUB_ENV
          echo "NGINX_IMAGE_NAME=$DOCKER_USERNAME/adaptive_learning_backend_nginx" >> $GITHUB_ENV
          echo "POSTGRES_IMAGE_NAME=$DOCKER_USERNAME/adaptive_learning_backend_postgres" >> $GITHUB_ENV
          echo "GIT_BRANCH=$GITHUB_REF" >> $GITHUB_ENV
          echo "GIT_COMMIT_SHA=$GITHUB_SHA" >> $GITHUB_ENV

      - name: DockerHub Login
        run: echo "$DOCKER_ACCESS_TOKEN" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - name: Set permissions for scripts
        run: find . -type f -iname "*.sh" -exec chmod +x {} \;
      
      - name: Test
        env:
          SECRETHUB_CREDENTIAL: ${{ secrets.SECRETHUB_CREDENTIAL }}
        run: make -B alltest